### ISSUE TITLE
socket unexpectedly disconnects

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1163]
Two issues were found in the last days consistently on the web-server logs of the staging deploy:

![bug - socket closing webserver 2019-11-13 14_19_39.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/d3d53f0b-5c75-4080-913a-4a4ef2da5a5c)

![bug - socket session disconneted webserver 2019-11-13 14_19_39.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/323720ed-07b6-4d4a-82d3-f6fa9f76ee63)

**Comment by sanderegg** [comment]
problem was fixed.
several issues are possible:
traefik needs to set some custom ssl headers so that socket.io can correctly upgrade the websocket from polling mode to websocket transport mode.
see [here](https://community.containo.us/t/how-to-make-websockets-work-with-traefik-2-0-setting-up-rancher/1732/2)
