### ISSUE TITLE
Review why services disconnect

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1190]
Why a service disconnect? Enumerate reasons? Define strategies to resolve each item. 

![Image Pasted at 2019-11-26 22-17.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/53b49b30-5a6a-429a-b51c-77cb9db256ff)

 - see log in time recorded in screenshot
 -

**Comment by sanderegg** [comment]
The issue was fixed when re-deploying staging/production cluster and the relative docker stacks.

One probable issue is that the traefik stack is not opening ports in ["host" mode](https://docs.docker.com/compose/compose-file/#ports).
This has the implications that:
1. the socket.io on the simcore platform cannot transit to websocket mode because of CORS issues (the server always sees the IP of the traefik node instead of the external IP)
2. the websocket in Visualizer times out after a few minutes of inactivity. (why this happens is unclear)

Setting the port in "host" mode fixes these issues. Probably setting some traefik middleware to set up the HEADERS correctly should fix the problem as well.

**Comment by sanderegg** [comment]
The reverse proxy **traefik** was adjusted to pass a ssl header such that socket.io is able to establish the websocket transport (see [info here](https://community.containo.us/t/how-to-make-websockets-work-with-traefik-2-0-setting-up-rancher/1732/2))
