### ISSUE TITLE
Extend framework to store application based user settings

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#1920]
**USER STORY:**

Larger applications like sim4life have application wide settings that should be made persistent in a database or in a S3 user-folder as a file. For example, when a user starts sim4life, he expects to always have the same preferences (color-schema, render-quality, 3d-projection mode)

**DEFINITION OF DONE:**

Platform provides an API similar to retrieve or publish that provides a service with data that can be interpredet as application prefernces (h5 files, json, ...) 

**EXAMPLE:**

The sim4life use case above.

**Comment by mguidon** [comment]
@pcrespov @GitHK As former and current SM. How do we handle developer requests?

**Comment by GitHK** [comment]
I would propose adding a new API endpoint on the `dynamic-sidecar` for this purpose, since this would be the perfect interface. Something similar to:
- `POST /simcore/global-store` to save the data under the form of a dictionary
- `GET /simcore/global-store` fetch previously stored data

The `dynamic-sidecar` will store store the data using `service_key` (+ `service_version`?) in the database.

**Comment by pcrespov** [comment]
User settings now stored in backend
