### ISSUE TITLE
Error when resetting password

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-simcore#2568]
hi guys, I am trying to sign in to https://osparc.speag.com/ and can't sign in to my account, apparently my password doesn't match the one in my notes. When I try to reset my password I get a message that my API rate limit limit is exceeded. even though I didn't get any password reset email so I am not sure how I used the API. I waited a few minutes and tried again but no luck. is this a bug or do i need to wait for an hour or until tomorrow or something?

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/unpau5zgdid38qgekpsab3dc1y) *by `@goren`*._

**Comment by KZzizzle** [comment]
I can reproduce this error by trying to reset my password. The frontend shows API rate limit exceeded in the pop-up. Dev-tools shows:
```/v0/auth/reset-password:1 Failed to load resource: the server responded with a status of 429 ()```

```{"data": null, "error": {"logs": [{"message": "Method Not Allowed", "level": "ERROR", "logger": "user"}], "errors": [{"code": "HTTPMethodNotAllowed", "message": "Method Not Allowed", "resource": null, "field": null}], "status": 405}}```

**Comment by pcrespov** [comment]
@GitHK could you please check whether this failure related to the [``global_rate_limit_route`` decorator in ``reset_password``](https://github.com/ITISFoundation/osparc-simcore/blob/3502447d5e6518c0c44d543b031c612c165969a1/services/web/server/src/simcore_service_webserver/login/handlers.py#L177)? 

@KZzizzle gets a strange combiation since the status in the header is [429: Too many requests](https://httpstatuses.com/429) but the body returns a [405 method not allowed](https://httpstatuses.com/405). The latter is typically when the http verb is wrong e.g. GET instead of a POST or so ...

**Comment by GitHK** [comment]
That is very very strange. Tried out to emulate it but I get the correct status on safari and chrome. The only strage thing I see is the url `/v0/auth/reset-password:1`. This should not work.

By the way at 8:58 the endpoint will work again. I've blocked it for 1 hour. If they need to reset the password we can reboot the webserver.

**Comment by odeimaiz** [comment]
The error in the backend
https://monitoring.osparc.speag.com/graylog/messages/graylog_0/6614e380-2527-11ec-bc34-0242ac120009

**Comment by KZzizzle** [comment]
this is now fixed
