### ISSUE TITLE
fix bug in API that limits to 2GB

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3263]
Python API client cannot upload >2GB?? 

NOTE: @sanderegg claims with ``curl`` worked and in some deployes client does work as well

**Comment by sanderegg** [comment]
## Api-server
- new entriypoints: forward webserver API to storage or storage API
## API-Client
- generate the raw client (the user of the client would have to get the multipart links, upload, complete)
- wrap the generated client so that this upload process wraps the complexity (/upload file as usual)
