### ISSUE TITLE
Total number of anonymous users who are redirected to o²S²PARC

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#3412]
Created this issue to group all the info we have related to this metric.

In march, this was the Prometheus query used and associated graph.
![image](https://user-images.githubusercontent.com/18575092/193820041-2ed339ae-c2a5-401f-837a-6689414d278d.png)
Problem with the above is that the p2e tests were not subtracted (that was done manually)

**Comment by elisabettai** [comment]
Now the same query gives the following graph.

![image](https://user-images.githubusercontent.com/18575092/193820763-5ace4342-1139-4a8d-9498-43803429d9bd.png)

Did I understand well @mrnicegyu11 that you know what was the increase between Aug and Sep 8 and that you fixed something related to that? Sorry if you've explained that already yesterday, but I thought it's better to write it down here.

**Comment by sanderegg** [comment]
@elisabettai I take you are refering to graph 1.
Yes that is correct, 
```rate``` [docs](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) "calculates the per second average rate of increase of the time series in the range vector". **Breaks in monotonicity (such as counter resets due to target restarts) are automatically adjusted for.**
so ```rate(http_requests_total(...([3h])``` computes the # requests per second over the last 3 hours for each point in the time series. Since it's multiplied by a day (in seconds), we get the number of http requests per day.
From there my guess is that the p2p tests are running about 150 times per day, which would be the baseline (it runs every 3 hours, so 8 times per day, in January March, I guess were about 9+1 sequential tests and 1*9 parallel test, so that would be 8 * (9+1 + 9)=152 tests per day. I think that makes sense.

**Comment by sanderegg** [comment]
the sum part is because the webserver is restarted from time to time, and is therefore a new instance. so we sum them.
I think with the change of @mrnicegyu11 regarding the tasks, this should also apply. And I searched a bit yesterday and there as well we should sum the individual rates to get the grand total

**Comment by elisabettai** [comment]
@sanderegg gave me this PromQP query, which works on master to get very close to the "Total number of anonymous users who are redirected to o²S²PARC" and filters out the e2e test.
`sum(rate(http_requests_total{service_name="webserver", endpoint="/study/{id}", simcore_user_agent!="puppeteer"}[3h])*60*60*24)`
The graph on master looks like this:
![image](https://user-images.githubusercontent.com/18575092/197576756-e52c11c2-5334-48b9-9c54-ac0dc19e2e15.png)

Looks good to me (value should be 0), not sure why it was not like that before the Oct. 5.

The change is not in production yet (it only reached [staging_switzer1](https://github.com/ITISFoundation/osparc-simcore/releases/tag/staging_switzer1)).

@mrnicegyu11, would you mind updating the grafana dashboards with that query ("Number of redirected anonymous users per day")? Should we wait that the required changes reach production?
