### ISSUE TITLE
Doc on how *exactly and without doubt* determine if a serice is legacy

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#3964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### User Story

My last info from @GitHK (and @sanderegg w.r.t. `integration-version`) is that the only way to determine whether a service is dy-sidecar-enabled (and thus not legacy) is to inspect the docker image labels and check if there is `simcore.service.paths-mapping`. If the docker image label is there, it is a dy-sidecar service. Otherwise, it is a legacy service.

Now, for `registry.osparc.io/simcore/services/dynamic/dsistudio-app:2.0.0` @elisabettai has informed me that ` This one is the "backend" of dsistudio-web 2.0.0, so it's not legacy (the same as dsistudio-web is not legacy)`. But, according to the info above, since there is no `simcore.service.paths-mapping`, I assumed it is a legacy service.

Could we please document (in this issue potentially, but better in a proper doc) how to make it clear with absolute certainty what is or isnt a dynamic service? Thanks a lot!

### Definition of Done

There is a documentation on how to make it clear with absolute certainty what is or isnt a dynamic service

**Comment by elisabettai** [comment]
@mrnicegyu11, thank you for this.
I am not sure how to address this one, since dsistudio is an example of particular service, a osparc-ui module. There's more explanation on gitlab (in case it's useful, I can send you the link).

An osparc-ui module consists of two services, a web proxy web and the actual application app. I wouldn't know if there's an equivalent of `simcore.service.paths-mapping` for the "-app" part of those services. Maybe @mguidon  would know more. Also, the `-app` part of the service normally is not published (so it's not accessible to users).

If I give you a strategy that relies on having "-app" in the service name would be useful for you to  *exactly and without doubt* determine* if a service is legacy?

**Comment by sanderegg** [comment]
@mrnicegyu11 
@elisabettai is right.

1. a osparc dynamic service is ```modern``` or ```dynamic-sidecar```-powered if it does contain the label ```simcore.service.paths-mapping```.
2. osparc dynamic services can be made of 1 or N docker containers, and only the **main** service (containing the web server) is labelled that way as this is the one containing the data. The **dependent** services do not contain that label (confirmed by running ```docker inspect registry.osparc.io/simcore/services/dynamic/dsistudio-app:2.0.0 | jq ".[0].Config.Labels"```)
3. the only link you can find is in the **main** service, there is a label ```simcore.service.compose-spec``` that contain the docker-compose used to run the service **and** its dependencies.

--> In order to find the legacy services here is a pseudo code:
- list all the services
- get all the ones with ```simcore.service.paths-mapping```, these are *modern*
- in these check for the label ```simcore.service.compose-spec```, if it's available look for the services in there and remove them from original list as well
- what remains are the legacy services

**Comment by mrnicegyu11** [comment]
thanks for this pseudocode!
