### ISSUE TITLE
Maintenance: revisit logging in osparc

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4079]
This is a sub issue from https://github.com/ITISFoundation/osparc-issues/issues/675

A random module in osparc-simcore is logged as 
```python

import logging
NOTE
logger = logging.getLogger(__name__)

# ...
logger.info(...)
```
now, revisit the following random points (not in a specific order)  about **logging in osparc-simcore repo**:

- [x] **formatting**: normalize log messages
     - https://github.com/ITISFoundation/osparc-simcore/issues/2157
     - https://github.com/ITISFoundation/osparc-simcore/issues/2782
- [x] Include [**extra** fields](https://docs.python.org/3/library/logging.html#logging.Logger.debug) in logs (e.g. users) that can be easily parseable (e.g. in graylog fields)
  - https://github.com/ITISFoundation/osparc-ops-environments/pull/138 
  - https://github.com/ITISFoundation/osparc-simcore/pull/4114
  - https://github.com/ITISFoundation/osparc-simcore/pull/4136
  - https://github.com/ITISFoundation/osparc-ops-environments/pull/142
  - https://github.com/ITISFoundation/osparc-simcore/pull/4169
- [x] Doc [**OEC** (osparc error code)](https://github.com/ITISFoundation/osparc-simcore/blob/master/packages/service-library/src/servicelib/error_codes.py#L1-L7): what are OECs, how and when to use them
  - [ ] We want to add them to the extra logging field 
- [x] Review and doc **logging policies**: when and how to log
   - when to log and when not to log (e.g. raising exception)?
   - how? when to use what log level? what to log? security?
      -  https://github.com/ITISFoundation/osparc-simcore/issues/3148
   - which log level needs to be set by deploy/service (e.g. DEBUG in master?)
   - REview code and adapt all logs to policies
- [x] **cleanup** ``servicelib.logging_utils``: review existing tools, remove duplicates/unused tools, make them more useful
- [x] **non-blocking** logs in **async** apps: revisit https://www.zopatista.com/python/2019/05/11/asyncio-logging/
  -  [21 Apr 2023] Did some performance tests and didn't get any performance gains
- [ ] or consider 3rd party library e.g. https://github.com/Delgan/loguru ?
- [x] graylog colormap of error logs per service
   - see comment bellow
- [x] See security issue with log config. See details [here](https://sonarcloud.io/project/security_hotspots?id=ITISFoundation_osparc-simcore&hotspots=AYBvvM1a_8r2OU53wDIJ)

NOTE: This is a first step towards starting going to **zero-errors logs policy** that we want to implement

**Comment by matusdrobuliak66** [comment]
Now a dashboard in Graylog can be setup which gives us additional information if they are populated:
![image](https://user-images.githubusercontent.com/60785969/233630574-9387bcfd-9ec3-4408-a0fd-8a5c629bb057.png)

**Comment by matusdrobuliak66** [comment]
Putting just for reference: https://www.structlog.org/en/stable/index.html# - might be a good library to consider

**Comment by matusdrobuliak66** [comment]
Reviewing security hotspot reported by Sonar Cloud:
- unauthorized users might have access to the logs, either because they are stored in an insecure location or because the application gives access to them. -> **Only uses with password & connected to secure network has access**
- the logs contain sensitive information on a production server. This can happen when the logger is in debug mode. -> **We do not have turned on debug mode in production deployment. Also we do not log sensitive data.**
- the log can grow without limit. This can happen when additional information is written into logs every time a user performs an action and the user can perform the action as many times as he/she wants. -> **Yes, currently num. of logs is not limited, but we are handling it for now**
- the logs do not contain enough information to understand the damage an attacker might have inflicted. The loggers mode (info, warn, error) might filter out important information. They might not print contextual information like the precise time of events or the server hostname. -> **We log many contextual information like precise time, server hostname, service name, syslogs** 
- the logs are only stored locally instead of being backed or replicated. -> **Yes, currently we do not backup logs, which is not optimal**
