### ISSUE TITLE
Github hotfix release action: SHA of hotfix should not be identical to SHA

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#4598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If one wants to release a hotfix to production, which incidental is identical to the "regular" staging code, which itself has been a hotfix from master to staging, things get weird. Now, please dont complain that this is a corner-case, @matusdrobuliak66 tells me this is part of the "normal release procedures". 

The `BRANCH_NAME` determination in the github action fails, claiming the commit is found on a `hotfix_staging_*` branch, instead of the intended `hotfix_v*`, where the commit is also present.

Then, the github action if-clause `if: contains(env.BRANCH_NAME, 'remotes/origin/hotfix_v')` returns false, and the github-action that rolls out docker images to dockerhub will decide to release the current `staging` images to `production` by retagging, instead of using the hotfix branch. Which is very weird and hard to understand.

### Expected Behavior

Possible mitigations:
- The github action asserts that the hotfix-commit-sha is only on one `git ref`. I dont see a proper reason to hotfix something that is also on another `ref`, like master or staging.
- The branch-determination logic is improved, if two `refs` match a commit the correct one is somehow picked and everything is handled gracefully. Currently if two refs match one commit, a randon ref is chosen as the branch.
- Change `if: contains(env.BRANCH_NAME, 'remotes/origin/hotfix_v')` to `if: contains(env.BRANCH_NAME, 'remotes/origin/hotfix_')`, which is more permissive and would have handled this double-error properly
...

### Steps To Reproduce

I recommend against reproducing this.

### Anything else?

Personal opinion: We should be less hacky with "hotfixes", and acknowledge that currently we need to kick users out to release sanely. This hackery causes more pains than gains and steals hours that could be used coding improvements.

**Comment by sanderegg** [comment]
@mrnicegyu11 @matusdrobuliak66 
I do see your pain and I'm sorry about that but:
- the hotfixing procedure was originally only for bringing production hotfixes,
- this code side-tracked to also be possible for staging because of some sudden need,
- a hotfix to production should be done in the following way (which was originally also defined as such in the README available for it):
  - from the current production tag, you create a new branch
  - bringing the necessary hotfix(es) in,
  - letting the CI complete this and check that it works correctly

Now moving hotfixes from staging to production, is a new path so I am not particularly astonished that it does not work out of the box. Defining it as a bug, well I do not agree since it was never supposed to work as such but I guess that is always something related to point of views. Nevertheless I can see the need for improving it. Beware of dragons.

**Comment by matusdrobuliak66** [comment]
Yes, we went through it more deeply just to understand the confusion. But in the end, both branches were pointing to the same commit SHA, so everything was deployed correctly. 

I think for now it is enough that we know about it, but I guess this was maybe the first time we did it because master to staging deployment was blocked which doesn't happen often.

**Comment by sanderegg** [comment]
no, it is not the first time, @pcrespov knows. but as I said, what you did was not part of what that system was built for and needs adjustment if this becomes common usage.
