### ISSUE TITLE
1024 vs 1000 for RAM calculation

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-simcore#5028]
### Current Behavior

This hurts me every time a look at it:

![image](https://github.com/ITISFoundation/osparc-simcore/assets/33161876/8f920f6e-1fa7-4afd-8f98-568561c59d4f)

**Comment by elisabettai** [comment]
Mmh, I wonder if this is due to [this issue](https://github.com/ITISFoundation/osparc-simcore/pull/4808) and [PR](https://github.com/ITISFoundation/osparc-simcore/pull/4808).

How it is displayed is actually correct: GB=gigabytes (they are in decimal system). What we normally think in binary system are actually gibibytes (GiB).
![image](https://github.com/ITISFoundation/osparc-simcore/assets/18575092/a36e52b3-0a71-4746-b137-b32120ea1223)

**Comment by mguidon** [comment]
I understand where it is coming but I think when used for RAM storage, we should stay with powers of 2. But maybe the Tiktok generation sees that the other way round...

**Comment by sanderegg** [comment]
or just change the unit to GiB

**Comment by pcrespov** [comment]
> or just change the unit to GiB

and add a tooltip with an explanation?

**Comment by mguidon** [comment]
I would prefer the 1024 system. If we cannot agree on this then lets at least make sure `SIMCORE_MEMORY_BYTES_LIMIT` ends up in the 1024 system when we edit the number in the frontend. Beacuse this is what I assume everywhere.
