### ISSUE TITLE
Activity Manager UI

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-simcore#525]
We need to keep in mind the Control Center described in #502. Users need to be aware of how much and what kind of resources they are consuming, and even be able to free them somehow. These new views could be the entry point to this coming feature.

New requirements:
* Showing max memory usage
* Showing status (loading, ready -> then showing hardware usage, running, queued)

Please get inspired in windows task manager pannel. <---

Definition document -> https://docs.google.com/document/d/1xRfoxQoJ_3IdyOMJOjO2kYrb9Szixc-oOAGIlwfXuVY/edit?usp=sharing

child of #502

**Comment by pcrespov** [comment]
@odeimaiz In your description you have missed many of the points I thought we agreed during our discussion. e.g.
- Services should not be defined as "one-to-one with registry". e.g. modeler is not a one-to-one, or a full study will be used in in the future as a single service
- The service tab should not only list available services but the state of running services (e.g. estimated/actual resource usage, )
- We do not speak about `files` but instead call it `data`. IMHO the naming is important here because here we should inform the user about the resources available and consumed in terms of not only disk space but also allocated memory. i.e. the data can occupy space when is stored persistently or during some operation during a limited period of time.

**Comment by ignapas** [comment]
I am back! @KZzizzle @pcrespov 10 min of quality time together?

**Comment by KZzizzle** [comment]
Yes! Meeting Niels (and other new hires) for lunch today at noon but I am free all afternoon (I guess I should get back no later than 1:30)

**Comment by ignapas** [comment]
![last-activity.gif](https://images.zenhubusercontent.com/5caefb2eecad11531cc41380/3bd5ff83-d608-4273-9f48-70df33eb1f0e)
