### ISSUE TITLE
glitches with folders

### ISSUE THREAD

**Issue by calys** [ITISFoundation/osparc-simcore#6386]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which deploy/s?

sim4life-staging.cloud

### Current Behavior

There are a few glitches with folders:

- Empty folders (incl. the root folder) are first displayed with an arrow in the tree. If the user tries to expand the arrow, the arrow disappears. We would expect that the arrow is never there in the first place.
- there is a "Loading..." project card displayed for a few (or sometimes a lot of) milliseconds even when there is nothing to load (I know that this is not related to folders, but it becomes more obvious when one navigates inside empty folders, which happens often.
- sometimes, the projects in a given folder are not displayed (this is a much more serious problem...)
- sometimes, the path (Dashboard / folder 1 / folder 2 / etc...) is not displayed (that is also very bad....)

![Image](https://github.com/user-attachments/assets/6c920bc7-8a29-41c4-a9ef-9d92cb91cacd)
![Image](https://github.com/user-attachments/assets/72f1f993-7791-4658-8982-6cfca5e7ee05)
![Image](https://github.com/user-attachments/assets/cdd007fa-aa61-4a44-95e6-62fba0eb15a5)

**Comment by odeimaiz** [comment]
Issues 3 and 4 were fixed and released to staging last Wednesday.

Regarding issues 1 and 2, it's a matter of how much data the frontend fetches. At the moment it's kind of a lazy loading, the data is only loaded when the user requests it:
- 1) fetch the children folders when you expand the parent folder. It might not have any children, so the arrow disappears.
- 2) fetch the projects within a folder. We show the loading card while fetching the data and remove it when the respond reaches the frontend, the folder might also be empty, Since we don't cache this response, every time you switch folders we reload the projects
